name: Deploy to ragtest

on:
  push:
    branches: [ "main" ]   # 메인 브랜치 푸시 시 배포 (원하면 변경)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 서버로 소스 업로드 (scp/rsync 느낌)
      - name: Upload project to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "/opt/ragtest"
          rm: true   # 서버의 타겟 폴더 비우고 업로드(원치 않으면 제거)

      # 서버에서 Docker 빌드 & 컨테이너 재기동
      - name: Remote docker build & restart
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            set -e
            cd /opt/ragtest
            docker build -t ragtest:latest .
            # 기존 컨테이너 중지/삭제(없으면 무시)
            docker stop ragtest || true
            docker rm ragtest || true
            # 새 컨테이너 기동
            docker run -d --name ragtest \
              -p 5000:5000 \
              --restart unless-stopped \
              ragtest:latest
            # 상태 확인
            sleep 2
            docker ps --filter "name=ragtest"